### ISSUE TITLE
UI Overlapped in decryption popup

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Tessercube-Android#10]
![IMG_8483](https://user-images.githubusercontent.com/6687437/63771804-b211d300-c88c-11e9-9689-ffc5ae649c8a.png)
How to reproduce:

Encrypted something and decrypt it with in 'moments ago'

**Comment by Tlaster** [comment]
Fixed by 38c33c7a0e9cfc8ccb3d8b4a28d889ff603c36a6, do we need to release a new version for it?

**Comment by Tedko** [comment]
> Fixed by [38c33c7](https://github.com/DimensionDev/Tessercube-Android/commit/38c33c7a0e9cfc8ccb3d8b4a28d889ff603c36a6), do we need to release a new version for it?

Yes let's release one.
