### ISSUE TITLE
Support FDroid 

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Tessercube-Android#2]

**Comment by Tlaster** [comment]
It's a long time ago and FDroid still not responding https://gitlab.com/fdroid/rfp/issues/1009

**Comment by Tedko** [comment]
Do they have twitter email or sth? Let’s ask them directly...

**Comment by Tedko** [comment]
Or pin them again in the thread

**Comment by Tlaster** [comment]
Maybe we need to open a pull request manually at https://gitlab.com/fdroid/fdroiddata

**Comment by Tedko** [comment]
> Maybe we need to open a pull request manually at https://gitlab.com/fdroid/fdroiddata

@Tlaster yeah go ahead lets create a pr

**Comment by Poussinou** [comment]
You switched back to a regular build.gradle file instead of build.gradle.kts, or maybe I miss something here? If it's the case, your app can probably be build now.

**Comment by Tedko** [comment]
Thanks!

**Comment by Tedko** [comment]
> You switched back to a regular build.gradle file instead of build.gradle.kts, or maybe I miss something here? If it's the case, your app can probably be build now.

@Tlaster Checkout this
