### ISSUE TITLE
Cannot install updated version

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Tessercube-Android#3]
![photo_2019-06-06_23-24-30](https://user-images.githubusercontent.com/6687437/59045427-a24ca900-88b2-11e9-826c-6759799c10f0.jpg)
![photo_2019-06-06_23-24-33](https://user-images.githubusercontent.com/6687437/59045428-a24ca900-88b2-11e9-8169-593aefddf5ba.jpg)
![photo_2019-06-06_23-24-36](https://user-images.githubusercontent.com/6687437/59045431-a24ca900-88b2-11e9-8276-2a3c635db2fa.jpg)

Not sure why
Android Version:9

**Comment by Tedko** [comment]
not reproduced yet

**Comment by yisiliu** [comment]
Try uninstalling Google Play Protect

**Comment by Tedko** [comment]
![Image](https://i.imgur.com/Sk0U4w5.jpg)

Seems like fixed by the latest version. I will close this issue later if there’s no report of reproduction of the same issue

**Comment by Tedko** [comment]
No report of this problem so far.
